#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-Math-Random-ISAAC
Version  : 1.004
Release  : 24
URL      : https://cpan.metacpan.org/authors/id/J/JA/JAWNSY/Math-Random-ISAAC-1.004.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/J/JA/JAWNSY/Math-Random-ISAAC-1.004.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmath-random-isaac-perl/libmath-random-isaac-perl_1.004-1.debian.tar.xz
Summary  : 'Perl interface to the ISAAC PRNG algorithm'
Group    : Development/Tools
License  : Artistic-2.0 GPL-3.0 MIT
Requires: perl-Math-Random-ISAAC-license = %{version}-%{release}
Requires: perl-Math-Random-ISAAC-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::NoWarnings)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution Math-Random-ISAAC,
version 1.004:
Perl interface to the ISAAC PRNG algorithm

%package dev
Summary: dev components for the perl-Math-Random-ISAAC package.
Group: Development
Provides: perl-Math-Random-ISAAC-devel = %{version}-%{release}
Requires: perl-Math-Random-ISAAC = %{version}-%{release}

%description dev
dev components for the perl-Math-Random-ISAAC package.


%package license
Summary: license components for the perl-Math-Random-ISAAC package.
Group: Default

%description license
license components for the perl-Math-Random-ISAAC package.


%package perl
Summary: perl components for the perl-Math-Random-ISAAC package.
Group: Default
Requires: perl-Math-Random-ISAAC = %{version}-%{release}

%description perl
perl components for the perl-Math-Random-ISAAC package.


%prep
%setup -q -n Math-Random-ISAAC-1.004
cd %{_builddir}
tar xf %{_sourcedir}/libmath-random-isaac-perl_1.004-1.debian.tar.xz
cd %{_builddir}/Math-Random-ISAAC-1.004
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Math-Random-ISAAC-1.004/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Math-Random-ISAAC
cp %{_builddir}/Math-Random-ISAAC-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Math-Random-ISAAC/b46e09ed0be834bcddac2c482e0626787091333d || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Random::ISAAC.3
/usr/share/man/man3/Math::Random::ISAAC::PP.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Math-Random-ISAAC/b46e09ed0be834bcddac2c482e0626787091333d

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
