#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Math-Random-ISAAC
Version  : 1.004
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/J/JA/JAWNSY/Math-Random-ISAAC-1.004.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/J/JA/JAWNSY/Math-Random-ISAAC-1.004.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmath-random-isaac-perl/libmath-random-isaac-perl_1.004-1.debian.tar.xz
Summary  : 'Perl interface to the ISAAC PRNG algorithm'
Group    : Development/Tools
License  : Artistic-2.0 GPL-3.0 MIT
Requires: perl-Math-Random-ISAAC-license
Requires: perl-Math-Random-ISAAC-man
Requires: perl(Test::NoWarnings)
BuildRequires : perl(Test::NoWarnings)

%description
This archive contains the distribution Math-Random-ISAAC,
version 1.004:
Perl interface to the ISAAC PRNG algorithm

%package license
Summary: license components for the perl-Math-Random-ISAAC package.
Group: Default

%description license
license components for the perl-Math-Random-ISAAC package.


%package man
Summary: man components for the perl-Math-Random-ISAAC package.
Group: Default

%description man
man components for the perl-Math-Random-ISAAC package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Math-Random-ISAAC-1.004
mkdir -p %{_topdir}/BUILD/Math-Random-ISAAC-1.004/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Math-Random-ISAAC-1.004/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Math-Random-ISAAC
cp LICENSE %{buildroot}/usr/share/doc/perl-Math-Random-ISAAC/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Math/Random/ISAAC.pm
/usr/lib/perl5/site_perl/5.26.1/Math/Random/ISAAC/PP.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Math-Random-ISAAC/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Random::ISAAC.3
/usr/share/man/man3/Math::Random::ISAAC::PP.3
